/*
Owner = Antonescu Radu-Ion
Year = 2016

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef __TIMER_H__
#define __TIMER_H__

#include <stdint.h>

#ifndef CPU_FREQ
#define CPU_FREQ 48000000
#endif

/* Timer registers */
#define STCTL     *(unsigned int*)(0xE000E000 + 0x10)
#define STRELOAD  *(unsigned int*)(0xE000E000 + 0x14)
#define STCURRENT *(unsigned int*)(0xE000E000 + 0x18)

/* NVIC */
#define INTEN     *(unsigned int *)(0xE000E000 + 0x100)
#define SYSTICK_INT_BIT (1 << )

/* Timer flags */
#define STCOUNT  (1 << 16) /* RO */
#define STCLKSRC (1 << 2)  /* 1 = internal */
#define STINTEN  (1 << 1)  /* interrupt enable */
#define STEN     (1 << 0)  /* enable multiple shoots */

void sys_tick_handler(void);
void timer_init(void);
void timer_pause(void);
int in_timer_list(uint8_t id);

#endif

